@extends('public.layout')
@section('title', 'Customize your package · Aling Chona')
@section('content')
<script src="{{ asset('js/catalog-order.js') }}?v={{ filemtime(public_path('js/catalog-order.js')) }}"></script>
<div class="storefront"><a class="back-link" href="{{ route('public.order.index') }}">← All packages</a><header class="store-heading"><div><h1>Make it yours</h1><p>Choose the layers, extras and design for {{ $product->product_name }}.</p></div></header><nav class="store-progress" aria-label="Order progress"><a href="{{ route('public.order.index') }}">1. Choose package</a><span aria-current="step">2. Customize</span><span>3. Contact & pickup</span><span>4. Staff review</span></nav>
<form method="POST" action="{{ route('public.package.save',['product'=>$product,'line'=>$line]) }}" enctype="multipart/form-data" data-package-editor data-editor-url="{{ route('public.package.draft',['product'=>$product,'line'=>$line]) }}" class="catalog-selection-form customize-form" x-data="catalogOrder({{ Js::from($products) }}, {{ Js::from([$editor]) }}, {{ Js::from(route('public.order.quote')) }}, false, {{ Js::from('bakery-package-'.$line) }})" @submit="if (uploading || busy) { $event.preventDefault(); error='Wait for your reference photos to finish saving.'; } else { busy=true; }">
@csrf<noscript><p>Enable JavaScript to customize this package.</p></noscript>
<div class="customize-main"><template x-for="(item,index) in items" :key="item.uid">@include('partials.package-line-fields',['staff'=>false,'customizing'=>true])</template></div>
<aside class="customize-summary" aria-label="Price summary"><h2>Your package</h2>@if($product->photo_path)<img src="{{ asset('storage/'.$product->photo_path) }}" alt="{{ $product->product_name }}" class="customize-photo" width="400" height="400">@endif<p>{{ $product->product_name }}</p><dl><div><dt>Package & extras</dt><dd x-text="money(total())"></dd></div><div><dt>50% deposit</dt><dd x-text="money(Math.round(total()*100/2)/100)"></dd></div></dl><p class="form-hint">Fixed prices. Themes and design requests do not add a charge. Extra quantities apply to this whole package line.</p><p role="status" x-text="uploading ? 'Saving reference photos…' : uploadStatus"></p><p class="field-error" role="alert" x-show="error" x-text="error" x-cloak></p><button class="ui-button primary" :disabled="uploading || busy" type="submit" x-text="busy ? 'Saving…' : 'Save package to order'"></button><a class="ui-button quiet" href="{{ route('public.order.index') }}">Back to packages</a></aside>
</form></div>
@endsection
