@extends('layouts.admin')
@section('title', 'Expense audit history')
@section('content')
<div class="workspace"><header class="workspace-heading"><div><a class="back-link" href="{{ route('expenses.index') }}">← Expenses</a><h1>Expense audit history</h1><p>Read-only records of creation, edits and deletion.</p></div></header>
<form method="GET" class="workspace-filters"><div><label for="audit-expense">Expense ID</label><input id="audit-expense" name="expense_id" type="number" min="1" value="{{ request('expense_id') }}"></div><div><label for="audit-action">Action</label><select id="audit-action" name="action"><option value="">All actions</option>@foreach(['created','edited','voided','legacy_baseline'] as $action)<option @selected(request('action')===$action) value="{{ $action }}">{{ ucfirst(str_replace('_',' ',$action)) }}</option>@endforeach</select></div></form>
<div class="workspace-summary"><span>{{ number_format($audits->total()) }} audit records @if(request()->hasAny(['expense_id', 'action'])) · <a class="text-cocoa-500 hover:text-cocoa-700 underline text-xs font-medium ml-1" href="{{ route('expenses.history') }}">Reset filters</a>@endif</span></div>
<div class="workspace-table table-scroll" role="region" aria-label="Expense audit records" tabindex="0"><table><thead><tr><th>Recorded at</th><th>Expense</th><th>Action / actor</th><th>Change details</th><th>Reason</th></tr></thead><tbody>
@forelse($audits as $audit)<tr><td class="nowrap">{{ $audit->recorded_at->format('M d, Y H:i:s') }}</td><td><a class="record-link" href="{{ route('expenses.show',$audit->expense_id) }}">#{{ $audit->expense_id }} · {{ $audit->expense->description }}</a></td><td>{{ ucfirst(str_replace('_',' ',$audit->action)) }}<br>{{ $audit->actor?->full_name ?? 'System baseline' }}</td><td><details><summary>Before / after values</summary><dl class="audit-values">@foreach($audit->after_values ?? [] as $field=>$value)@if(!in_array($field,['submission_key']))<div><dt>{{ str_replace('_',' ',$field) }}</dt><dd><span>{{ is_array($audit->before_values[$field] ?? null) ? json_encode($audit->before_values[$field]) : ($audit->before_values[$field] ?? '—') }}</span> → <strong>{{ is_array($value) ? json_encode($value) : ($value ?? '—') }}</strong></dd></div>@endif @endforeach</dl></details></td><td>{{ $audit->reason ?? '—' }}</td></tr>@empty<tr><td colspan="5" class="empty-state">No audit records match these filters.</td></tr>@endforelse
</tbody></table></div><x-workspace-pagination :records="$audits" /></div>
@endsection
