@extends('layouts.admin')
@section('title', 'Inventory & supplies')
@section('content')
<div class="workspace"><header class="workspace-heading"><div><h1>Inventory & supplies</h1><p>Shared ingredients and packaging, across every package.</p></div><a class="ui-button primary" href="{{ route('inventory.create','receipt') }}"><x-icon name="plus" /> Receive stock</a></header>
<div class="workspace-toolbar"><div class="workspace-actions"><a class="ui-button" href="{{ route('inventory.create','usage') }}">Record usage / waste</a><a class="ui-button" href="{{ route('inventory.create','stocktake') }}">Stocktake</a><a class="ui-button" href="{{ route('supplies.create') }}">Add supply</a></div><a class="ui-button quiet" href="{{ route('inventory.history') }}">Movement history</a></div>
<form method="GET" class="workspace-filters" aria-label="Filter supplies"><div class="filter-search"><label for="supply-q">Search</label><input id="supply-q" name="q" value="{{ request('q') }}" placeholder="Supply name"></div><div><label for="supply-category">Category</label><select id="supply-category" name="category"><option value="">All categories</option>@foreach(['ingredients','packaging'] as $category)<option value="{{ $category }}" @selected(request('category')===$category)>{{ ucfirst($category) }}</option>@endforeach</select></div><div><label for="supply-status">Stock status</label><select id="supply-status" name="status"><option value="">All stock levels</option>@foreach(['healthy'=>'In stock','low'=>'Low stock','out'=>'Out of stock'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div><div><label for="supply-active">Activity</label><select id="supply-active" name="active">@foreach(['active'=>'Active','inactive'=>'Inactive','all'=>'All supplies'] as $value=>$label)<option value="{{ $value }}" @selected(request('active','active')===$value)>{{ $label }}</option>@endforeach</select></div><input type="hidden" name="sort" value="{{ request('sort','supply_name') }}"><input type="hidden" name="direction" value="{{ request('direction','asc') }}"><button class="ui-button">Apply</button><a class="ui-button quiet" href="{{ route('supplies.index') }}">Reset</a></form>
<div class="workspace-table table-scroll" role="region" aria-label="Supplies table" tabindex="0"><table><thead><tr><th><x-sort-heading column="supply_name" label="Supply" /></th><th><x-sort-heading column="category" label="Category" /></th><th><x-sort-heading column="unit" label="Unit" /></th><th class="numeric"><x-sort-heading column="current_quantity" label="On hand" /></th><th class="numeric"><x-sort-heading column="reorder_level" label="Reorder at" /></th><th>Stock status</th><th>Actions</th></tr></thead><tbody>
@forelse($supplies as $supply)<tr><td><a class="record-link" href="{{ route('supplies.show',$supply) }}">{{ $supply->supply_name }}</a>@unless($supply->is_active)<span class="status">Inactive</span>@endunless</td><td>{{ ucfirst($supply->category) }}</td><td>{{ $supply->unit }}</td><td class="numeric">{{ number_format($supply->current_quantity,2) }}</td><td class="numeric">{{ number_format($supply->reorder_level,2) }}</td><td>@if($supply->current_quantity == 0)<span class="status status-danger">Out of stock</span>@elseif($supply->is_low_stock)<span class="status status-attention">Low stock</span>@else<span class="status status-success">In stock</span>@endif</td><td><details class="row-actions"><summary>Actions</summary><div><a href="{{ route('supplies.show',$supply) }}">Details</a><a href="{{ route('supplies.edit',$supply) }}">Edit</a><a href="{{ route('inventory.history',['supply_id'=>$supply->id]) }}">History</a></div></details></td></tr>@empty<tr><td colspan="7" class="empty-state">No supplies match these filters. <a href="{{ route('supplies.index') }}">Clear filters</a> or add a supply.</td></tr>@endforelse
</tbody></table></div><x-workspace-pagination :records="$supplies" /></div>
@endsection
