@extends('layouts.admin')
@section('title', ['receipt'=>'Receive stock','usage'=>'Record usage / waste','waste'=>'Record usage / waste','stocktake'=>'Stocktake'][$type])
@section('content')
<script src="{{ asset('js/inventory-workspace.js') }}?v={{ filemtime(public_path('js/inventory-workspace.js')) }}"></script>
<div class="workspace" x-data="stockOperation(@js($type), @js($initialLines), @js(route('supplies.lookup')))">
<header class="workspace-heading"><div><a class="back-link" href="{{ route('supplies.index') }}">← Inventory</a><h1>{{ ['receipt'=>'Receive stock','usage'=>'Record usage / waste','waste'=>'Record usage / waste','stocktake'=>'Stocktake'][$type] }}</h1><p>{{ $type === 'stocktake' ? 'Enter actual counted quantities. Changes are checked again when you post.' : 'Add supplies and review the stock changes before posting.' }}</p></div></header>
<form class="workspace-form" data-safe-form action="{{ route('inventory.store') }}" method="POST" @submit="if (!lines.length) { $event.preventDefault(); error = 'Add at least one supply.'; $refs.search.focus(); }">
@csrf<input type="hidden" name="submission_key" value="{{ old('submission_key',(string) Str::uuid()) }}">
<div class="form-grid">
@if(in_array($type,['usage','waste']))<div><label for="operation-type">Operation</label><select id="operation-type" name="type" x-model="type"><option value="usage">Normal usage</option><option value="waste">Waste / spoilage</option></select></div>@else<input type="hidden" name="type" :value="type">@endif
<div><label for="operation_date">{{ $type === 'receipt' ? 'Received date' : 'Effective date' }}</label><input type="date" id="operation_date" name="operation_date" required value="{{ old('operation_date',now()->toDateString()) }}"></div>
@if($type === 'receipt')<div><label for="supplier">Supplier (optional)</label><input id="supplier" name="supplier" maxlength="255" value="{{ old('supplier') }}"></div><div><label for="delivery_reference">Delivery reference (optional)</label><input id="delivery_reference" name="delivery_reference" maxlength="255" value="{{ old('delivery_reference') }}"></div>@endif
</div>
<div class="supply-search"><label for="find-supply">Find a supply</label><div class="workspace-actions"><input x-ref="search" id="find-supply" x-model="search" @input.debounce.250ms="lookup()" @keydown.escape="results=[]" placeholder="Start typing a supply name" autocomplete="off" aria-controls="supply-search-results" :aria-expanded="results.length > 0"><button type="button" class="ui-button" @click="lookup()">Search supplies</button></div>
<p role="status" x-text="loading ? 'Searching…' : searched && !results.length ? 'No matching supplies. Try another name.' : ''"></p>
<ul id="supply-search-results" class="supply-results" x-show="results.length" x-cloak><template x-for="supply in results" :key="supply.id"><li><button type="button" @click="add(supply)" :disabled="lines.some(line => Number(line.supply_id) === supply.id)"><span x-text="supply.supply_name"></span><span x-text="supply.current_quantity + ' ' + supply.unit + ' on hand'"></span><span x-text="lines.some(line => Number(line.supply_id) === supply.id) ? 'Added' : '+ Add'"></span></button></li></template></ul></div>
<p class="field-error" role="alert" x-show="error" x-text="error" x-cloak></p>
<div class="workspace-table table-scroll" role="region" aria-label="Stock operation rows" tabindex="0"><table class="batch-table"><thead><tr><th>Supply</th><th>Unit</th><th class="numeric">Recorded</th><th x-text="type === 'stocktake' ? 'Counted quantity' : 'Quantity'"></th><th class="numeric">Change</th><th class="numeric">Expected stock</th><th>Actions</th></tr></thead><tbody>
<template x-for="(line,index) in lines" :key="line.supply_id"><tr><td><strong x-text="line.name"></strong><input type="hidden" :name="'lines['+index+'][supply_id]'" :value="line.supply_id"><input type="hidden" :name="'lines['+index+'][expected_version]'" :value="line.expected_version"></td><td x-text="line.unit"></td><td class="numeric" x-text="format(line.current_quantity)"></td><td><label class="sr-only" :for="'stock-quantity-'+line.supply_id" x-text="line.name + ' quantity'"></label><input :id="'stock-quantity-'+line.supply_id" :name="'lines['+index+'][quantity]'" type="number" inputmode="decimal" :min="type === 'stocktake' ? 0 : 0.01" max="99999999.99" step="0.01" required x-model="line.quantity"></td><td class="numeric" x-text="format(delta(line),true)"></td><td class="numeric" :class="after(line) < 0 ? 'field-error' : ''" x-text="format(after(line))"></td><td><button type="button" class="ui-button quiet" :aria-label="'Remove '+line.name" @click="lines.splice(index,1)">Remove</button><button type="button" class="ui-button quiet" x-show="type==='stocktake'" @click="refreshLine(line)" :aria-label="'Reload current stock for '+line.name">Reload stock</button></td></tr></template>
<tr x-show="!lines.length"><td colspan="7" class="empty-state">Search for supplies above to add the first row.</td></tr></tbody></table></div>
<div><label for="notes" x-text="['waste','stocktake'].includes(type) ? 'Reason / explanation' : 'Notes (optional)'"></label><textarea id="notes" name="notes" rows="2" maxlength="2000" :required="['waste','stocktake'].includes(type)">{{ old('notes') }}</textarea></div>
<div class="form-actions"><span x-text="lines.length + ' supplies · all rows post together'"></span><a class="ui-button" href="{{ route('supplies.index') }}">Cancel</a><button class="ui-button primary" :disabled="!lines.length" type="submit">Post stock operation</button><span role="status" data-submit-status></span></div>
</form></div>
@endsection
